/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_RMath */

#ifndef _Included_com_jni_RMath
#define _Included_com_jni_RMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_RMath
 * Method:    ppois
 * Signature: (DDII)D
 */
JNIEXPORT jdouble JNICALL Java_com_jni_RMath_ppois
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
