/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rmath_RMathNative */

#ifndef _Included_org_rmath_RMathNative
#define _Included_org_rmath_RMathNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rmath_RMathNative
 * Method:    dnorm4
 * Signature: (DDDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dnorm4
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    pnorm5
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_pnorm5
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qnorm5
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qnorm5
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dunif
 * Signature: (DDDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dunif
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    punif
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_punif
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qunif
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qunif
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dgamma
 * Signature: (DDDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dgamma
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    pgamma
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_pgamma
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qgamma
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qgamma
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dbeta
 * Signature: (DDDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dbeta
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    pbeta
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_pbeta
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qbeta
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qbeta
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dlnorm
 * Signature: (DDDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dlnorm
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    plnorm
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_plnorm
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qlnorm
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qlnorm
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dchisq
 * Signature: (DDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dchisq
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    pchisq
 * Signature: (DDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_pchisq
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qchisq
 * Signature: (DDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qchisq
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dnchisq
 * Signature: (DDDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dnchisq
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    pnchisq
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_pnchisq
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qnchisq
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qnchisq
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    df
 * Signature: (DDDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_df
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    pf
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_pf
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qf
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qf
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dt
 * Signature: (DDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dt
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    pt
 * Signature: (DDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_pt
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qt
 * Signature: (DDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qt
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dbinom
 * Signature: (DDDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dbinom
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    pbinom
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_pbinom
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qbinom
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qbinom
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dcauchy
 * Signature: (DDDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dcauchy
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    pcauchy
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_pcauchy
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qcauchy
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qcauchy
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dexp
 * Signature: (DDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dexp
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    pexp
 * Signature: (DDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_pexp
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qexp
 * Signature: (DDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qexp
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dgeom
 * Signature: (DDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dgeom
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    pgeom
 * Signature: (DDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_pgeom
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qgeom
 * Signature: (DDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qgeom
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dhyper
 * Signature: (DDDDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dhyper
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    phyper
 * Signature: (DDDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_phyper
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qhyper
 * Signature: (DDDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qhyper
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dnbinom
 * Signature: (DDDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dnbinom
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    pnbinom
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_pnbinom
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qnbinom
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qnbinom
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dpois
 * Signature: (DDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dpois
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    ppois
 * Signature: (DDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_ppois
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qpois
 * Signature: (DDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qpois
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dweibull
 * Signature: (DDDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dweibull
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    pweibull
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_pweibull
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qweibull
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qweibull
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dlogis
 * Signature: (DDDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dlogis
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    plogis
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_plogis
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qlogis
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qlogis
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dnbeta
 * Signature: (DDDDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dnbeta
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    pnbeta
 * Signature: (DDDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_pnbeta
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qnbeta
 * Signature: (DDDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qnbeta
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dnf
 * Signature: (DDDDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dnf
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    pnf
 * Signature: (DDDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_pnf
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qnf
 * Signature: (DDDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qnf
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dnt
 * Signature: (DDDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dnt
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    pnt
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_pnt
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qnt
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qnt
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    ptukey
 * Signature: (DDDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_ptukey
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qtukey
 * Signature: (DDDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qtukey
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dwilcox
 * Signature: (DDDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dwilcox
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    pwilcox
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_pwilcox
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qwilcox
 * Signature: (DDDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qwilcox
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    dsignrank
 * Signature: (DDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_dsignrank
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    psignrank
 * Signature: (DDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_psignrank
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint);

/*
 * Class:     org_rmath_RMathNative
 * Method:    qsignrank
 * Signature: (DDII)D
 */
JNIEXPORT jdouble JNICALL Java_org_rmath_RMathNative_qsignrank
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
